name: Testing NDVI APIGateway

on:
  push:
    branches: [ master ]

jobs:
  pytest:
    name: Linter and Pytest
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Linter & Pytest
        env:
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_EVENT_NAME: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_RUN_ID $GITHUB_REPOSITORY $GITHUB_EVENT_NAME"

      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install cryptography==38.0.4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Unit Test with pytest
        if: always()
        continue-on-error: true
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          POLYGON: ${{ vars.POLYGON }}
          API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}

        run: |
          echo "$PYTHONPATH $PWD $POLYGON $GITHUB_WORKSPACE"
          pytest tests_ndvi/conftest.py -vv -o log_cli=true --html=pytest-report.html

      - name: Publish HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report.html


  dockerImage:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    environment: Dev
    needs: pytest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/test-ndvi-gateway

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: unit-test-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
